### PR TITLE
feat: redesign with astro.build

### LINKED ISSUE #43: Feat: Redesign Landing
# Goals 
- Visualy more appealing and paving the way for new design line
- Better UX
- Better SEO and other tech. metrics

# Sub-tasks
- [x] #38 
- [x] #39
- [x] #40  
- [x] #41 
- [x] #42 
- [x] #45  
- [x] #46
- [x] #47 
- [x] #48

### PR DESCRIPTION
**Pull request by tristanremy**
Closes #43

### CODE REVIEW

**Comment by TheKinrar** [comment]
(Just in case you didn't notice: your node_modules folder and the bootstrap sources are included in this PR)

**Comment by LudoGranger** [comment]
Hello @tristanremy, 
My feedback
- overall cleaner & engaging !

- FOMO effect 🤣 it's really an investor thing. But the overall UX looks like the normal, we need to get to WAOW here. And I think we can have it with minor changes: 
1. Landing page entry -> check example here https://www.june.so/
2. Effect with buttons / formating -> https://www.hyperline.co/
- maybe "request access" -> need to click, then enter your email

Page 1: 
- Lead machine and behavioral targeting solution for B2B sales. for "Lead supply and behavioral targeting for B2B sales."
- "Built with sales in 200+ mid-market B2B companies + logo" is not well integrated". Maybe do not put any color on the built... and try to have it right away on the first page"

Page advocacy: 
"Leadbay Early Supporters Early Supporters Speak Out" -> "Sales already love us"

Request early access to leadbay:
- Enter your email / request access & not join. Same button than 1st page



Also, check all of this - I especially like https://www.hyperline.co/ . Just perfect

[Inspiration folder](https://drive.google.com/drive/u/0/folders/1eKGDDgmHra_r72EZAwRwJXDLC9HPt6Oq)
[Wip website](https://leadbay.github.io/landingpage/)
Website inspiration: 
https://www.folk.app/
https://www.askdialog.com/
https://www.getokko.app/
https://www.lemlist.com/
https://www.unrevealed.tech/
https://www.mutinyhq.com/
https://www.june.so/
https://www.calixa.io/
http://beam.so/
https://getapron.com/
https://en.modjo.ai/
https://www.pocus.com/
https://www.apollo.io/
https://www.hyperline.co/ 
https://www.getokko.app/
[Alan](https://alan.com/) - lots of empty space. Big buttons. Big titles. (I can immagine less text).
[Swile](https://www.swile.co/en?gclid=Cj0KCQjwu-KiBhCsARIsAPztUF2dXAdjg8IkZgXIXW0ciagP34Aw1Ef8Tu36Y-nO8vLtjU54xIxhw_oaAlv4EALw_wcB&utm_medium=paid&utm_content=70107000000LTwMAAW&utm_source=google_ads&utm_campaign=paid_ggads_fr_brand_swile_keyword) - looks modern, animated. Big letters. Lots of empty space. (I can imagine less “in your face” animations all over the screen, but ok)
[Dialog](https://www.askdialog.com/) - harmonious combination of violet, pale gray and white. Lots of empty space. On the other hand content is problematic - not clear what they offer. Looks really unfinished, but for the stage it’s OK.
[June](https://www.june.so/) - confident design with lots of white space, big titles, harmonious colors. Round egdes. Animations make it modern.
[Lemlist](https://www.lemlist.com/) - I like that there is almost no text. All the convicing is done with screenshots and gifs. Big titles. Empty spaces. I like the textrues. On the other hand I don’t like their blue color (blue-on-black ugly) and also to get to this clarity of message to be able to have no text takes a lot of work and time we don’t have now.
[Pennylane](https://www.pennylane.com/fr/?utm_term=pennylane&utm_campaign=Marque%20Pennylane&utm_source=adwords&utm_medium=ppc&hsa_acc=3994605419&hsa_cam=9831785008&hsa_grp=114878266246&hsa_ad=640210658789&hsa_src=g&hsa_tgt=kwd-329808826025&hsa_kw=pennylane&hsa_mt=e&hsa_net=adwords&hsa_ver=3&gclid=Cj0KCQjwu-KiBhCsARIsAPztUF09D3ATHw_UDjFKLC2ClRs8M_f0ewfOzkK2-GsO52T58oXIPpXRFqIaAiVnEALw_wcB) - I like the focus on scheenshots and the adequacy between creenshots colors and the website colors. The whole thing is kind-of blended like a part of the same texture. However there is too much text, and this costs a ton to make (and like lemlist - is difficult to maintain).
Others I dislike
[Salesforce](https://www.salesforce.com/) - looks like a website from the 90s. Fading screenshots look like somebody made a PowerPoint file and exported it to HTML. Pale colors and gradients make it look cheap, like something that is not really product i.e. it has this Microsoft vibe of something you use because you have to, not because it really works or because you love it.
[Payfit](https://payfit.com/fr/?utm_feeditemid=&utm_device=c&utm_term=payfit&utm_source=google&utm_medium=ppc&utm_campaign=Search-Brand_FR_EXACT_TIM_PRO&hsa_cam=1714442526&hsa_grp=67733879275&hsa_mt=e&hsa_src=g&hsa_ad=405887316422&hsa_acc=8747059790&hsa_net=adwords&hsa_kw=payfit&hsa_tgt=kwd-312290476709&hsa_ver=3&gad=1&gclid=Cj0KCQjwu-KiBhCsARIsAPztUF3Mx-gPnE9r3zoyACFBfq50ArXmnMesHqX8OBYQeW12Z2PDeda0HUoaAg5rEALw_wcB) - pale colors, fonts somehow clashing with shapes, possibly too thin, too edgy. Looks like a booring business tool you really don’t want, but have to use. You want to get away from the website the moment it loads.

**Comment by LudoGranger** [comment]
@tristanremy - j'y pense tardivement - mais essaie d'avoir une cohérence avec le travail de design qui a été fait sur le deck https://docs.google.com/presentation/d/1VHFnT3cyGQtbrasiT_j6oIa5HWMMoQppzkJwGwLeZ4o/edit#slide=id.g249f9f8d9e3_0_100. 
Si trop tard, ne te fais pas de soucis pour ça

**Comment by tristanremy** [comment]
Oui, j'aurai aussi dû te demander, mea culpa, je fais au mieux et j'ajuste pour te poser plus de questions sur tes besoins la prochaine fois 😉

**Comment by tristanremy** [comment]
@milstan Ok, je suis d'accord avec tout ça, c'est mon idée première aussi 😉

**Comment by milstan** [comment]
@tristanremy : J'ai discuté avec @LudoGranger et il semble que le site actuel (avec toute la value-proposition bien expliqué) nous a bsien servi pour attirer des premiers clients, mais que pour finaliser le fundraising, vis-à-vise des investisseurs, il nous faut un site moins pedagogique qui crée plus de mystère sur ce qu'on offre. De [ce](https://www.harvey.ai/) type.

Voyons comment on peut, avec moindre effort, basculer vers un site "mystère" pour le moment (nous reviendrons à un site orienté clients à l'autumne) au lancement du produit.

**Comment by tristanremy** [comment]
@LudoGranger Your requested changes (loom video) should be implemented on the preview environnement. Could you approve this PR if everything looks fine to you here : https://deploy-preview-44--leadbay-landingpage.netlify.app/ ?

**Pull request merged**
