### PR TITLE
website changes requested by Ludo

### LINKED ISSUE #35: Landing page - content review & suggest to update
1st page: 
"Lead machine and behavioral targeting solution for B2B sales." -> The platform that supplies B2B sales with ai-powered qualified leads

2nd page: 
"Set up your smart lead machine in 3 clicks" -> "parameter with leadbay AI suggestions your ideal customer profile "
"Define your target personas, connect with your current database, cherry-pick your sample clients, and let Leadbay extrapolate to find lookalikes."

3rd page: 
"Lists discovery, new highly qualified leads every week" -> Leads discovery, new highly qualified leads every week"
"Our AI will carefully send you suggestions based on your traffic and likelihood prediction from your internal ecosystem." -> "Leadbay AI will predict which leads is more aiming to close this week based on leads events."

4th page: 
"Configure your own AI Scoring and spend your time only on leads that matter" -> keep
"Set your scoring criteria and let our AI system collect signals from lead behavior and give you smart cluers to help you contact the right lead at the right time." -> "Set your scoring criteria and let leadbay AI collect signals from leads behaviour to let you contact the right lead at the right time."

5th page: 
"Last sales-perf tool you'll ever need
We are rolling out early-adopter access in batches. Sign-up to get your place in line. We'll be in touch soon."
-> "Request early access to leadbay + mail"

"Subscribe to our newsletter" -> to our monthly letter
@milstan

### PR DESCRIPTION
**Pull request by milstan**
Close #35 #33

### CODE REVIEW

**Comment by milstan** [comment]
Here is a quick patch to add content Ludo needs on the website (logos and testemonials). 

@tristanremy please review (feel free to modify) and merge. Ludo needs this ASAP and I will be traveling today and offline.

@LudoGranger coordinate directly with Tristan if you need any changes as I am offline most of the day today.

**Comment by milstan** [comment]
Just tried but I don't have the pro version needed to add team members. 

I'll try to find a moment later to change the password and send you the password

**Comment by LudoGranger** [comment]
Screenshot 2023-06-21 at 16 03 58

On peut faire plus beau @tristanremy , see my example in the feed

**Comment by LudoGranger** [comment]
@tristanremy 
Page 2 "Parameter your ideal customer profile with leadbay AI suggestions" -> 'Parameter your Ideal Customer Profile with leadbay AI"

**Pull request merged**
